# Generated by Django 5.2.8 on 2025-11-11 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pengguna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('satpam', 'Satpam'), ('tamu', 'Tamu')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Satpam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('nik', models.CharField(max_length=20, unique=True)),
                ('alamat', models.TextField()),
                ('no_hp', models.CharField(max_length=15)),
                ('shift', models.CharField(choices=[('pagi', 'Pagi'), ('siang', 'Siang'), ('malam', 'Malam')], max_length=20)),
            ],
        ),
    ]
